[package]
name = "ruby-marshal-derive"
version = "0.1.0"
license = "MIT OR BSD-2-Clause"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
quote = "1.0.23"
syn = "1.0.107"
